### ISSUE TITLE
How to generate a valid BIP39 24-word wallet for Brave Rewards?

### ISSUE THREAD

**Issue by xanoni** [jonathansampson/brave-tools#5]
I want to play with the Brave Rewards feature, but after generating a wallet the browser doesn't show me my BIP39 phrase. Thus, I did the following.

1. went to `brave://rewards/`
2. clicked "Manage your wallet"
3. clicked "Restore"
4. entered a newly generated BIP39 mnemonic from https://iancoleman.io/bip39/
5. clicked "Restore" (at the bottom)

However, I'm getting below error message. What did I do wrong?

**Comment by jonathansampson** [comment]
@xanoni I don't believe you can restore an ad hoc wallet. The wallet must first be created _by Brave_ to be used in Brave Rewards. No backup codes are provided any longer in Brave Rewards; I believe this (in more detail) is provided in the UI of the application itself.

**Comment by xanoni** [comment]
Ok. Sad.
